# Generated by Django 3.1 on 2021-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
