# Generated by Django 3.1 on 2021-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dropbox_outputs_share_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
