# Generated by Django 3.1 on 2021-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_rate_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_required',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
