# Generated by Django 3.1 on 2021-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210411_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chunk_size_override',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
