# Generated by Django 3.1 on 2021-04-06 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
