# Generated by Django 3.1 on 2021-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20210406_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='reply',
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='attachments',
            field=models.ManyToManyField(to='ticketing.TicketAttachment'),
        ),
    ]
