# Generated by Django 3.1 on 2021-05-11 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20210511_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='attachments',
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketreply'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
