# Generated by Django 3.1 on 2021-05-12 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20210511_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketreply'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
