# Generated by Django 3.1 on 2021-05-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20210512_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='date_created',
        ),
    ]
