# Generated by Django 3.1 on 2021-05-14 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_remove_ticketattachment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
