# Generated by Django 3.1 on 2021-02-02 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='config_name')),
                ('is_active', models.BooleanField(default=False, max_length=150, null=True, verbose_name='is_active')),
                ('paypal_setting', models.JSONField(blank=True, null=True)),
                ('client_app_setting', models.JSONField(blank=True, null=True)),
                ('system_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='online', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocketConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=200, null=True, verbose_name='channel')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='group')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
