# Generated by Django 3.1 on 2021-03-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ban_disposable_emails',
            field=models.BooleanField(default=False, max_length=150, null=True),
        ),
    ]
