# Generated by Django 3.1 on 2021-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('coupon', 'Coupon'), ('credit_refund', 'Credit Refund')], default='paypal', max_length=100, null=True),
        ),
    ]
