# Generated by Django 3.1 on 2021-03-14 15:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210302_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpackage',
            name='label_color',
            field=colorfield.fields.ColorField(blank=True, default='#DF3F60', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='show_in_dashboard',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFF', max_length=18, null=True),
        ),
    ]
