# Generated by Django 3.1 on 2021-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210314_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('coupon', 'Coupon'), ('credit_refund', 'Credit Refund'), ('payment_refund', 'Payment Refund'), ('credit_transfer', 'Credit Transfer'), ('promotion', 'promotion')], default='paypal', max_length=100, null=True),
        ),
    ]
