# Generated by Django 3.1 on 2021-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline_tasks_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='cpu_usage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='deadline_task_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='frame_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='render_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='render_time_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='renderplan',
            name='rate_per_min',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
