# Generated by Django 3.1 on 2021-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210220_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='frame_list',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
