# Generated by Django 3.1 on 2021-03-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210302_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='renderplan',
            name='deadline_machine_limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
