# Generated by Django 3.1 on 2021-03-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderplan',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
