# Generated by Django 3.1 on 2021-03-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210310_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joberror',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='joberror',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='job.software'),
        ),
        migrations.AlterField(
            model_name='joberror',
            name='solution',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
