# Generated by Django 3.1 on 2021-03-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_renderplan_admin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderplan',
            name='deadline_priority',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
