# Generated by Django 3.1 on 2021-03-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_renderplan_deadline_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='error',
            field=models.ManyToManyField(blank=True, to='job.JobError'),
        ),
    ]
