# Generated by Django 3.1 on 2021-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20210316_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='joberror',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
