# Generated by Django 3.1 on 2021-06-25 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_jobstatus_is_upgradable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
